apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: aadb-website-interaction-agent-location
  description: Links to additional entities in the aadb-website-interaction-agent
    repository.
  annotations:
    github.com/project-slug: Bandwidth/aadb-website-interaction-agent
spec:
  targets:
    - ./component.yaml
